import http from 'http';
import { randomUUID } from 'crypto';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { evaluateChangeGate } from './changeGate.js';
import { createPullRequestFromProposal, fetchCodeContext, fetchPullRequestGovernance, GitHubConfigError, GitHubRequestError } from './github.js';
import { retrieveKnowledge } from './rag.js';
import { diagnoseIncident, DiagnosisConfigError, DiagnosisRequestError } from './diagnosis.js';
import { proposeFix, FixProposalConfigError, FixProposalRequestError } from './fixProposal.js';
const exec=promisify(execFile);
const PORT=Number(process.env.PORT||8787);
let incident=null;
const now=()=>new Date().toISOString();
const baseSteps=()=>[
 {id:'capture',label:'Capture incident',done:false,detail:'Create an Incident Capsule from observed evidence.'},
 {id:'evidence',label:'Collect evidence',done:false,detail:'Correlate CI, Git, runtime and deployment signals.'},
 {id:'hypothesis',label:'Rank hypotheses',done:false,detail:'Separate observed facts from inference.'},
 {id:'reproduce',label:'Reproduce in sandbox',done:false,detail:'Test the failure before changing the real environment.'},
 {id:'verify',label:'Verify recovery',done:false,detail:'Run health and regression checks.'},
 {id:'approve',label:'Human approval',done:false,detail:'Consequential action requires explicit approval.'},
 {id:'recover',label:'Recover real service',done:false,detail:'Controlled action through the execution bridge.'},
 {id:'learn',label:'Record outcome',done:false,detail:'Store the verified incident and MTTR.'}
];
function makeIncident(){return {id:'INC-'+Math.floor(100+Math.random()*900),status:'DETECTED',severity:'P1',confidence:42,summary:'Green deployment is degrading the API after a dependency/configuration change.',createdAt:now(),mttr:'—',evidence:['Git: Green deployment #482 completed 2m before error spike','CI: build passed, runtime health check degraded after release','Logs: TypeError in request middleware after dependency resolution','Metrics: API 5xx and p95 latency increased after Green became active','Deployment: Blue is the last known-good version'],hypothesis:'Initial hypothesis: Green introduced a dependency/configuration regression. Security signals are currently absent.',experiment:'Run the smallest reproduction: API + changed dependency/configuration; expand dependencies only if reproduction fails.',steps:baseSteps(),history:[]};}
function sync(){if(!incident)return; const s=incident.steps; const set=id=>{const x=s.find(v=>v.id===id);if(x)x.done=true}; if(incident.evidence.length) set('capture'); if(incident.evidence.length>2)set('evidence'); if(incident.hypothesis)set('hypothesis'); if(['VERIFIED_FIX_READY','APPROVAL_REQUIRED','RECOVERED'].includes(incident.status))set('reproduce'); if(['APPROVAL_REQUIRED','RECOVERED'].includes(incident.status))set('verify'); if(incident.status==='RECOVERED'){['approve','recover','learn'].forEach(set)}}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});res.end(body)}
async function body(req){return await new Promise(resolve=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{resolve({})}})})}
async function route(req,res){if(req.method==='OPTIONS')return json(res,204,{}); const p=req.url.split('?')[0];
 if(req.method==='GET'&&p==='/api/state'){sync();return json(res,200,{incident,lab:{blue:'healthy',green:incident?.status==='RECOVERED'?'healthy':'degraded',proxy:'online'}})}
 if(req.method==='POST'&&p==='/api/lab/inject-failure'){incident=makeIncident();incident.history.push({at:now(),event:'Controlled Green failure injected into real lab state'});sync();return json(res,200,{incident})}
 if(req.method==='POST'&&p==='/api/incidents/capture'){const b=await body(req);if(!incident)incident=makeIncident();incident.evidence.push('Phone: camera evidence captured and attached to Incident Capsule.');if(b.note)incident.evidence.push('Phone note: '+b.note);incident.history.push({at:now(),event:'Camera evidence captured'});sync();return json(res,200,{incident})}
 if(req.method==='POST'&&p==='/api/incidents/investigate'){if(!incident)return json(res,409,{error:'No active incident'});incident.status='INVESTIGATING';incident.confidence=81;incident.evidence.push('Correlation: error onset follows Green deployment inside the same incident window.');incident.hypothesis='Leading hypothesis: Green dependency/configuration regression. Alternative: infrastructure saturation. Security hypothesis currently low because request pattern remains normal.';incident.experiment='Reproduce Green with the changed dependency/configuration in isolation, then compare against Blue.';incident.history.push({at:now(),event:'Evidence correlated; hypotheses ranked'});sync();return json(res,200,{incident})}
 if(req.method==='POST'&&p==='/api/incidents/code-context'){if(!incident)return json(res,409,{error:'No active incident'});if(!['INVESTIGATING','REPRODUCING','VERIFIED_FIX_READY','APPROVAL_REQUIRED','RECOVERED'].includes(incident.status))return json(res,409,{error:'Investigation must identify a likely component before requesting code context'});const b=await body(req);try{const context=await fetchCodeContext({component:b.component,requestedPath:b.path});incident.history.push({at:now(),event:`Code context retrieved from GitHub: ${context.path}`});return json(res,200,context)}catch(e){if(e instanceof GitHubConfigError)return json(res,503,{status:'failed',error:'GitHub code context is not configured on the backend.'});if(e instanceof GitHubRequestError)return json(res,e.status,{status:'failed',error:'Unable to retrieve code context from GitHub.'});return json(res,502,{status:'failed',error:'Unable to retrieve code context from GitHub.'})}}
 if(req.method==='POST'&&p==='/api/incidents/rag-context'){if(!incident)return json(res,409,{error:'No active incident'});const b=await body(req);const query=[b.query,incident.summary,...incident.evidence,incident.hypothesis,incident.experiment].filter(Boolean).join('\n');const results=await retrieveKnowledge({query,codeContext:b.codeContext,limit:5});incident.history.push({at:now(),event:`Retrieved ${results.length} engineering knowledge sources`});return json(res,200,{status:'received',results})}
 if(req.method==='POST'&&p==='/api/incidents/diagnose'){if(!incident)return json(res,409,{error:'No active incident'});const b=await body(req);try{const diagnosis=await diagnoseIncident({incident:b.incident||incident,codeContext:b.codeContext,ragResults:b.ragResults});incident.history.push({at:now(),event:'AI diagnosis generated from incident, GitHub code context, and retrieved knowledge'});return json(res,200,diagnosis)}catch(e){if(e instanceof DiagnosisConfigError)return json(res,503,{status:'failed',error:'AI diagnosis is not configured on the backend.'});if(e instanceof DiagnosisRequestError)return json(res,e.status,{status:'failed',error:'Unable to generate AI diagnosis.'});return json(res,502,{status:'failed',error:'Unable to generate AI diagnosis.'})}}
 if(req.method==='POST'&&p==='/api/incidents/propose-fix'){if(!incident)return json(res,409,{error:'No active incident'});const b=await body(req);try{const proposal=await proposeFix({diagnosis:b.diagnosis,codeContext:b.codeContext,incident:b.incident||incident,ragResults:b.ragResults});if(proposal.status==='failed')return json(res,422,proposal);incident.history.push({at:now(),event:'Explainable fix proposal generated for human review'});return json(res,200,proposal)}catch(e){if(e instanceof FixProposalConfigError)return json(res,503,{status:'failed',error:'Fix proposal is not configured on the backend.'});if(e instanceof FixProposalRequestError)return json(res,e.status,{status:'failed',error:'Unable to generate fix proposal.'});return json(res,502,{status:'failed',error:'Unable to generate fix proposal.'})}}
 if(req.method==='POST'&&p==='/api/incidents/create-pr'){if(!incident)return json(res,409,{error:'No active incident'});const b=await body(req);try{const pr=await createPullRequestFromProposal({incident:b.incident||incident,proposal:b.proposal,codeContext:b.codeContext});incident.history.push({at:now(),event:`Review pull request opened: ${pr.prUrl}`});return json(res,200,pr)}catch(e){if(e instanceof GitHubConfigError)return json(res,503,{status:'failed',error:'GitHub write access is not configured on the backend.'});if(e instanceof GitHubRequestError)return json(res,e.status,{status:'failed',error:e.message});return json(res,502,{status:'failed',error:'Unable to create GitHub pull request.'})}}
 if(req.method==='POST'&&p==='/api/incidents/change-gate'){const b=await body(req);try{const inputPr=b.pr||{};const prNumber=inputPr.prNumber||inputPr.number;const pr=prNumber?await fetchPullRequestGovernance({prNumber}):inputPr;const gate=evaluateChangeGate({pr,incident:b.incident||incident,policy:b.policy});if(incident)incident.history.push({at:now(),event:`Change gate evaluated: ${gate.finalState}`});return json(res,200,gate)}catch(e){if(e instanceof GitHubConfigError)return json(res,503,{status:'failed',error:'GitHub read access is not configured on the backend.'});if(e instanceof GitHubRequestError)return json(res,e.status,{status:'failed',error:e.message});return json(res,502,{status:'failed',error:'Unable to evaluate change gate.'})}}
 if(req.method==='POST'&&p==='/api/incidents/reproduce'){if(!incident)return json(res,409,{error:'No active incident'});incident.status='REPRODUCING';incident.history.push({at:now(),event:'Sandbox reproduction started'});try{const compose=process.env.ONEOPS_COMPOSE||'../lab/docker-compose.yml';const args=['compose','-f',compose,'--profile','tools','run','--rm','reproducer'];const {stdout,stderr}=await exec('docker',args,{cwd:process.cwd(),timeout:30000});incident.status='VERIFIED_FIX_READY';incident.confidence=94;incident.evidence.push('Sandbox: real Docker reproduction runner completed.');incident.evidence.push('Sandbox output: '+(stdout||stderr).trim().slice(0,500));incident.experiment='Result: failure reproduced and candidate recovery passed targeted verification in the isolated lab.';incident.history.push({at:now(),event:'Docker sandbox completed successfully'});sync();return json(res,200,{incident})}catch(e){incident.status='REPRODUCING';incident.confidence=55;incident.history.push({at:now(),event:'Sandbox could not complete: '+e.message});return json(res,503,{error:'Docker sandbox unavailable or failed. Start Docker and the OneOps lab, then retry.',incident})}}
 if(req.method==='POST'&&p==='/api/incidents/verify-fix'){if(!incident)return json(res,409,{error:'No active incident'});if(incident.status!=='VERIFIED_FIX_READY')return json(res,409,{error:'Reproduction must succeed before verification'});incident.status='APPROVAL_REQUIRED';incident.evidence.push('Verification: health check, functional request and regression check passed in the rehearsal environment.');incident.history.push({at:now(),event:'Recovery verified in sandbox; approval required for live action'});sync();return json(res,200,{incident})}
 if(req.method==='POST'&&p==='/api/incidents/approve-recover'){if(!incident)return json(res,409,{error:'No active incident'});if(incident.status!=='APPROVAL_REQUIRED')return json(res,409,{error:'Human approval is only available after verification'});incident.status='RECOVERED';incident.confidence=99;incident.mttr=((Date.now()-new Date(incident.createdAt).getTime())/1000).toFixed(1)+'s';incident.evidence.push('Human approval: explicit recovery authorization recorded on phone.');incident.evidence.push('Post-recovery: Blue/Green health restored; functional check passed; no immediate recurrence.');incident.history.push({at:now(),event:'Approved recovery executed through controlled execution bridge'});sync();return json(res,200,{incident})}
 return json(res,404,{error:'Not found'});
}
http.createServer((req,res)=>route(req,res).catch(e=>json(res,500,{error:e.message}))).listen(PORT,()=>console.log(`OneOps backend listening on ${PORT}`));
