global:
  scrape_interval: 5s
scrape_configs:
  - job_name: oneops-blue
    metrics_path: /metrics
    static_configs: [{targets: ['blue:8080']}]
  - job_name: oneops-green
    metrics_path: /metrics
    static_configs: [{targets: ['green:8080']}]
